#server:
#  port: 8081
spring:
  application:
    name: spring-websocket-server-demo
  jmx:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
#        exclude: env, beans
  metrics:
    tags:
      application: ${spring.application.name}
    endpoints:
      enabled-by-default: false
      info:
        enabled: true
      health:
        enabled: true
      metrics:
        enabled: true
      env:
        enabled: true